[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "test-html-data-extract"
dynamic = ["version", "dependencies"]
description = 'PoC to test HTML table data extraction for DSB downloads'
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "U.N. Owen", email = "void@some.where" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]

[project.urls]
Documentation = "https://github.com/U.N. Owen/test-html-data-extract#readme"
Issues = "https://github.com/U.N. Owen/test-html-data-extract/issues"
Source = "https://github.com/U.N. Owen/test-html-data-extract"

[tool.hatch.version]
path = "src/test_html_data_extract/__about__.py"

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]

[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/test_html_data_extract tests}"

[tool.coverage.run]
source_pkgs = ["test_html_data_extract", "tests"]
branch = true
parallel = true
omit = [
  "src/test_html_data_extract/__about__.py",
]

[tool.coverage.paths]
test_html_data_extract = ["src/test_html_data_extract", "*/test-html-data-extract/src/test_html_data_extract"]
tests = ["tests", "*/test-html-data-extract/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
